spring:
  datasource:
    url: "jdbc:postgresql://${DB_URL:localhost:5435/geoviite}"
    username: "${DB_USERNAME:dev-geouser}"
    password: "${DB_PASSWORD:dev-geouser-password}"
logging:
  level:
    fi:
      fta:
        geoviite: debug
geoviite:
  i18n:
    override-path: "./src/main/resources/i18n/"
